# Travis-CI build for bash
# see travis-ci.org for details

language: generic

os: linux
dist: trusty
sudo: required

before_install:
  - sudo apt-get install -y --no-install-recommends
      texlive-base texlive-latex-base texlive-latex-extra 
      texlive-latex-recommended texlive-generic-extra
      texlive-fonts-recommended texlive-generic-recommended
      texlive-fonts-extra texlive-lang-cyrillic 

script:
  - cd spec
  - pdflatex -interaction=nonstopmode -halt-on-error bash.tex
  - pdflatex -interaction=nonstopmode -halt-on-error bash.tex
  - cd ..

deploy:
  provider: releases
  api_key: 
    secure: aTm8NeqtCzipw3nSlWIPJAZIACBS1QyLZZY48SaD7p+X9RP+AucN4EnWeB38iQG0Cm+xLKPyErmn1X6Rraz2b7ueSCHcrwZIuOO3CQ9/9qDR0u+bAFD+AxNYfacyFnyLYbrFekDGL8x0T8GKAVac9byknhKiMH0eDoh8slaIrmnZyamSWGPcylfmy2LKqyG5tfONxPJP88yBtTahX2ZwVbQfMJUvbKiZYmtGQJsdlD41O22Jv+hv7MoSw771ZAyit/Y7nV+xGJ10e3d5CBS22fcO6OKkUb7/M3vMhvBlBmGh+HMKpx4KRDAzlDi8bccKa9xFq4I2eL3t6C4M+1hJg/Ab1SU1TGCJVEfJok1G8M9FEDUqTA9AiVNiKcuERMnzfbWZeUjr0AR+8uBADWrhBxRP3p9K8jQ7o+qMAJtCKJARSbiMfHpd64rQZZ3xPlL6p1bRHRKO8jIlWUph9b9DLFTkNjyVwi+IvLm1Zd83QL2mQvDiJVxu9uziTUdiJSI4oBtNALDm8ON0QlBxYvwinzHhawKio/W5/ORcoOp2R7rky+bsBeLoJT7lLsdIcGIZDDgf07LpSRkJakuzLl47MVJeNvjjNBOZzJeNy1t4MaVOfV9zcE4EDo233bBcEiHlxktXg9nOKWbDNcHK3srCnMVrEzNY7tiUScfe5Lzj5YU=
  file: spec/bash.pdf
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true